UKCppLog: uk::log::UKLogger Class Reference
uk::log::UKLogger Class Reference
Basic C++ logger class. This class allows for easy logging from C++ (via macros). Logging is available before entering the main() function into a std::string buffer and can be send to a log file or will be dumped after process execution to the commandline.
#include <UKLogger.hpp>
Public Member Functions
UKLogger ()
Constructor.
virtual ~UKLogger ()
Destructor. Dump logging to the command line if not file name has been set.
void log (const std::string &severity, const std::string &kind, const std::string &func, const std::string &message, int line=0)
Log an entry. This member is thread save.
void setLogfileName (const std::string &name)
Set name of the logfile. If the logfile does exist, it will be deleted first. Should that fail, the application will fail immediately.
void setLogfileName (const std::filesystem::path &name)
Set name of the logfile. If the logfile does exist, it will be deleted first. Should that fail, the application will fail immediately.
UKLogger (const UKLogger &other)=delete
UKLogger & operator= (const UKLogger &other)=delete
UKLogger (const UKLogger &&other)=delete
UKLogger & operator= (const UKLogger &&other)=delete
Static Public Member Functions
static std::string getVersion ()
Get the version of the library.
Private Member Functions
void moveToTerminal ()
Private Attributes
std::mutex mMutex
std::string mInitialBuffer
std::ofstream mFileStream
bool mFileOpen {false}
Detailed Description
Basic C++ logger class. This class allows for easy logging from C++ (via macros). Logging is available before entering the main() function into a std::string buffer and can be send to a log file or will be dumped after process execution to the commandline.
When using a QObject by mEngine.rootContext()->setContextProperty("ukLogger", &uk::log::logger()); the singleton mechanism stops working and an additional instance is created. Move all Signal/Slot mechanisms used in connection with QML to UKLoggerObject.
Remarks
This class is implemented as a singleton.
In C++11 this class is fully thread save.
Definition at line 49 of file UKLogger.hpp.
Constructor & Destructor Documentation
UKLogger() [1/3]
uk::log::UKLogger::UKLogger ()
Constructor.
Definition at line 34 of file UKLogger.cpp.
References __PRETTY_FUNCTION__, and log().
~UKLogger()
uk::log::UKLogger::~UKLogger () virtual
Destructor. Dump logging to the command line if not file name has been set.
Definition at line 39 of file UKLogger.cpp.
References moveToTerminal().
UKLogger() [2/3]
uk::log::UKLogger::UKLogger (const UKLogger & other) delete
UKLogger() [3/3]
uk::log::UKLogger::UKLogger (const UKLogger && other) delete
Member Function Documentation
getVersion()
std::string uk::log::UKLogger::getVersion () static
Get the version of the library.
Returns
std::string: The version of the library.
Precondition
None.
Postcondition
Log line added.
Definition at line 158 of file UKLogger.cpp.
log()
void uk::log::UKLogger::log (const std::string & severity, const std::string & kind, const std::string & func, const std::string & message, int line = 0)
Log an entry. This member is thread save.
Parameters
[in] severity A string denoting the severity of the entry, eg "INFO" or "ERROR".
[in] kind A string denoting the kind of the entry, normally the class name.
[in] func The name of the function the entry is is logged in.
[in] message The logging message.
[in] line The line in the source code this entry is logged from.
Precondition
None.
Postcondition
Log line added.
Definition at line 41 of file UKLogger.cpp.
References mFileOpen, mFileStream, mInitialBuffer, and mMutex.
moveToTerminal()
void uk::log::UKLogger::moveToTerminal () private
Definition at line 160 of file UKLogger.cpp.
References mFileOpen, and mInitialBuffer.
operator=() [1/2]
UKLogger& uk::log::UKLogger::operator= (const UKLogger && other) delete
operator=() [2/2]
UKLogger& uk::log::UKLogger::operator= (const UKLogger & other) delete
setLogfileName() [1/2]
void uk::log::UKLogger::setLogfileName (const std::filesystem::path & name)
Set name of the logfile. If the logfile does exist, it will be deleted first. Should that fail, the application will fail immediately.
Parameters
[in] name Name of the logfile.
Precondition
None.
Postcondition
All subsequential logging is added to file.
Definition at line 154 of file UKLogger.cpp.
References setLogfileName().
setLogfileName() [2/2]
void uk::log::UKLogger::setLogfileName (const std::string & name)
Set name of the logfile. If the logfile does exist, it will be deleted first. Should that fail, the application will fail immediately.
Parameters
[in] name Name of the logfile.
Precondition
None.
Postcondition
All subsequential logging is added to file.
Definition at line 129 of file UKLogger.cpp.
References mFileOpen, mFileStream, mInitialBuffer, mMutex, UKLOG_FATAL, and UKLOG_WARN.
Member Data Documentation
mFileOpen
bool uk::log::UKLogger::mFileOpen {false} private
Definition at line 127 of file UKLogger.hpp.
mFileStream
std::ofstream uk::log::UKLogger::mFileStream private
Definition at line 126 of file UKLogger.hpp.
mInitialBuffer
std::string uk::log::UKLogger::mInitialBuffer private
Definition at line 125 of file UKLogger.hpp.
mMutex
std::mutex uk::log::UKLogger::mMutex private
Definition at line 124 of file UKLogger.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/UKCppLog/UKCppLog/src/UKLogger.hpp
/home/runner/work/UKCppLog/UKCppLog/src/UKLogger.cpp