name: cpplint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install cpplint
      run: |
        sudo apt-get update
        sudo apt-get install cpplint

    - uses: actions/checkout@v3

    - name: Run cpplint
      continue-on-error: true
      run: |
        cd ${{github.workspace}}/src
        cpplint --linelength=120 --filter=-build/include_subdir,-build/include_order,-build/c++11 *.cpp *.hpp
        
    - name: Show outputfile
      run: more ~/cpplint.txt