name: doxygen

on:
  workflow_dispatch:

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install doxygen graphviz

    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_DOCUMENTATION=ON
    
    - name: Run doxygen
      run: cmake --build ${{github.workspace}}/build --target doc_doxygen > ~/doxygen.txt 2>&1

    - name: Show outputfile
      run: more ~/doxygen.txt

    - name: Create .nojekyll
      run: touch ${{github.workspace}}/build/doc/html/.nojekyll
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: ${{github.workspace}}/build/doc/html